name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Tests
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
        export DENO_INSTALL="/home/runner/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        yarn install
        yarn test
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: jest-test-report
        path: coverage/
  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: GitHub
      run: |
        git config user.email "damianperera@outlook.com"
        git config user.name "GitHub Actions"
        hub auth $GITHUB_TOKEN
    - name: Build
      run: |
        yarn install
        yarn src
        yarn build
        echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        yarn version --patch
        hub push
        yarn publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docs:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build
      run: |
        yarn install
        yarn src
        yarn build
        yarn docs
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
